presubmits:
  # Kubernetes e2e correctness tests against EKS 1.11 build.
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-aws-eks-1-11-correctness
    branches:
    - master
    # NON-BLOCKING; only triggered manually, used for debugging.
    always_run: false
    optional: true
    labels:
      preset-service-account: "true"
      preset-kubernetes-e2e-aws-eks-common: "true"
      preset-kubernetes-e2e-aws-eks-1-11: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master
        imagePullPolicy: Always
        args:
          - --root=/go/src
          - --repo=k8s.io/kubernetes=$(PULL_REFS)
          - --repo=k8s.io/release
          - --upload=gs://kubernetes-jenkins/pr-logs
          - --timeout=200
          - --scenario=kubernetes_e2e
          - --
          - --build=bazel
          - --cluster=
          - --check-version-skew=false
          - --deployment=eks
          - --provider=eks
          - --gce-ssh=
          - --extract=local
          - --test_args=--ginkgo.focus=\[Feature:Performance\] --minStartupPods=8
          - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-aws-eks-1-11-correctness
          - --timeout=180m
