periodics:
- name: ci-structured-merge-diff-test
  interval: 12h
  labels:
    preset-service-account: "true"
  decorate: true
  extra_refs:
  - org: kubernetes-sigs
    repo: structured-merge-diff
    base_ref: master
    path_alias: sigs.k8s.io/structured-merge-diff
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master
      command:
      - go
      args:
      - test
      - ./...