# Gopkg.toml for k8s.io/test-infra

required = [
  "github.com/bazelbuild/bazel-gazelle/cmd/gazelle",
  "k8s.io/repo-infra/kazel",
  "github.com/client9/misspell/cmd/misspell",
  "github.com/golang/dep/cmd/dep",
  "github.com/golang/lint/golint",
  "github.com/jteeuwen/go-bindata/go-bindata",
  # Force dep to vendor the code generators, which
  # aren't imported just used at dev time. Picking a
  # subpackage with Go code won't be necessary once
  # https://github.com/golang/dep/pull/1545 is merged.
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
  # we don't need these but if we want the repo to build
  # with bazel we need to require them
  "k8s.io/code-generator/cmd/go-to-protobuf",
  "k8s.io/code-generator/cmd/import-boss",
  "k8s.io/code-generator/cmd/set-gen",
  "github.com/gogo/protobuf/vanity/command",
]

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

# Prevent dep from pruning build scripts and codegen templates
[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false
  unused-packages = false

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

# Hey bitbucket: join the modern world and allow https like everyone else in existence
[[override]]
  name = "bitbucket.org/ww/goautoneg"
  revision = "a547fc61f48d567d5b4ec6f8aee5573d8efce11d"
  source = "https://github.com/munnerz/goautoneg.git"

# Need override because release-1.12 and kubernetes-1.12.0 are not semver compliant
[[override]]
  name = "k8s.io/api"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/code-generator"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/client-go"
  version = "v9.0.0"

[[constraint]]
  name = "github.com/knative/build"
  revision = "v0.3.0"

[[constraint]]
  name = "github.com/docker/docker"
  # https://github.com/docker/docker-ce/blob/17.12/components/cli/vendor.conf
  # to update this check https://github.com/docker/docker-ce/blob/<tag>/components/cli/vendor.conf
  revision = "5e5fadb3c0201553929d4a6ea8dc8f9d8a1e56fe"

[[constraint]]
  name = "github.com/golang/dep"
  version = "v0.5.0"

[[constraint]]
  name = "cloud.google.com/go"
  version = ">=0.23.0"

[[constraint]]
  # used by both prow/plugins/buildifier and gazelle
  name = "github.com/bazelbuild/buildtools"
  revision = "80c7f0d45d7e40fa1f7362852697d4a03df557b3"

[[constraint]]
  name = "github.com/client9/misspell"
  revision = "9ce5d979ffdaca6385988d7ad1079a33ec942d20"

[[constraint]]
  name = "github.com/peterbourgon/diskv"
  revision= "2973218375c3d13162e1d3afe1708aaee318ef3f"

[[constraint]]
  name = "github.com/bazelbuild/bazel-gazelle"
  version = "0.16.0"

[[constraint]]
  branch = "master"
  name = "github.com/joshdk/go-junit"

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  # latest, unlikely to change as go-bindata is no longer maintained
  revision = "6025e8de665b31fa74ab1a66f2cddd8c0abf887e"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  # ensure we're using an updated version, as sigs.k8s.io/yaml depends on it
  version = "2.2.1"

[[constraint]]
  name = "github.com/knative/build-pipeline"
  version = "0.1.0"
