periodics:
- interval: 30m
  name: ci-kubernetes-e2e-gce-ha-master
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=240
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --env=MULTIZONE=true
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-project=kubernetes-ha-master
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:HAMaster\] --minStartupPods=8
      - --timeout=220m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 24h
  name: ci-kubernetes-e2e-gce-min-node-permissions
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=520
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      # TODO(@ihmccreery): is this right?
      - --env=KUBE_GCE_NODE_SERVICE_ACCOUNT=min-node-permissions@k8s-min-node-permissions.iam.gserviceaccount.com
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-project=k8s-min-node-permissions
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=500m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master
