presubmits:
  kubernetes-sigs/gcp-compute-persistent-disk-csi-driver:
  - name: pull-gcp-compute-persistent-disk-csi-driver-e2e
    always_run: true
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20180927-6b4facbe6
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=20" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-e2e.sh"
        env:
        - name: ZONE
          value: us-central1-c
  - name: pull-gcp-compute-persistent-disk-csi-driver-sanity
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20180927-6b4facbe6
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-sanity.sh"
  - name: pull-gcp-compute-persistent-disk-csi-driver-unit
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20180927-6b4facbe6
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-unit.sh"
  - name: pull-gcp-compute-persistent-disk-csi-driver-verify
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20180927-6b4facbe6
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=10" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "hack/verify-all.sh"
  - name: pull-gcp-compute-persistent-disk-csi-driver-kubernetes-integration
    always_run: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master
        args:
        - "--repo=sigs.k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--clean"
        - "--timeout=60" # Minutes
        - "--scenario=execute"
        - "--" # end bootstrap args, scenario args below
        - "test/run-k8s-integration.sh"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
