presubmits:
  kubeflow/examples:
  - name: kubeflow-examples-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/kubeflow:
  - name: kubeflow-presubmit
    always_run: true         # Run for every PR, or only when requested.
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/pytorch-operator:
  - name: kubeflow-pytorch-operator-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/reporting:
  - name: kubeflow-reporting-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/website:
  - name: kubeflow-website-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/testing:
  - name: kubeflow-testing-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/tf-operator:
  - name: kubeflow-tf-operator-presubmit
    always_run: true         # Run for every PR, or only when requested.
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/katib:
  - name: kubeflow-katib-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/experimental-kvc:
  - name: kubeflow-experimental-kvc-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/experimental-seldon:
  - name: kubeflow-experimental-seldon-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/experimental-beagle:
  - name: kubeflow-experimental-beagle-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/caffe2-operator:
  - name: kubeflow-caffe2-operator-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/kubebench:
  - name: kubeflow-kubebench-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/mpi-operator:
  - name: kubeflow-mpi-operator-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/chainer-operator:
  - name: kubeflow-chainer-operator-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/mxnet-operator:
  - name: kubeflow-mxnet-operator-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/arena:
  - name: kubeflow-arena-presubmit
    always_run: true         # Run for every PR, or only when requested.
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/pipelines:
  - name: kubeflow-pipeline-build-image
    always_run: true
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-1.10
        command:
        - ./test/presubmit-tests.sh
        args:
        - --workflow_file
        - build_image.yaml
    run_after_success:
    - name: kubeflow-pipeline-e2e-test
      always_run: true
      decorate: true
      labels:
        preset-service-account: "true"
      spec:
        containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-1.10
          command:
          - ./test/presubmit-tests-with-pipeline-deployment.sh
          args:
          - --workflow_file
          - e2e_test_gke_v2.yaml
          - --test_result_folder
          - e2e_test
    - name: kubeflow-pipeline-sample-test
      always_run: true
      decorate: true
      skip_report: true
      labels:
        preset-service-account: "true"
      spec:
        containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-1.10
          command:
          - ./test/presubmit-tests-with-pipeline-deployment.sh
          args:
          - --workflow_file
          - sample_test_v2.yaml
          - --test_result_folder
          - sample_test
          - --timeout
          - "3600"
    - name: kubeflow-pipeline-e2e-test-gce-minikube
      always_run: true
      decorate: true
      skip_report: true
      labels:
        preset-service-account: "true"
      spec:
        containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-1.10
          command:
          - ./test/presubmit-tests-gce-minikube.sh
          args:
          - --workflow_file
          - e2e_test_gke.yaml
          - --test_result_folder
          - e2e_test_gke
