postsubmits:
  kubeflow/examples:
  - name: kubeflow-examples-postsubmit
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/kubeflow:
  - name: kubeflow-postsubmit
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/pytorch-operator:
  - name: kubeflow-pytorch-operator-postsubmit
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/reporting:
  - name: kubeflow-reporting-postsubmit
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/website:
  - name: kubeflow-website-postsubmit
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/testing:
  - name: kubeflow-testing-postsubmit
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/tf-operator:
  - name: kubeflow-tf-operator-postsubmit
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/katib:
  - name: kubeflow-katib-postsubmit
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/experimental-kvc:
  - name: kubeflow-experimental-kvc-postsubmit
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/experimental-seldon:
  - name: kubeflow-experimental-seldon-postsubmit
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/experimental-beagle:
  - name: kubeflow-experimental-beagle-postsubmit
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/caffe2-operator:
  - name: kubeflow-caffe2-operator-postsubmit
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/kubebench:
  - name: kubeflow-kubebench-postsubmit
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/mpi-operator:
  - name: kubeflow-mpi-operator-postsubmit
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/chainer-operator:
  - name: kubeflow-chainer-operator-postsubmit
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/mxnet-operator:
  - name: kubeflow-mxnet-operator-postsubmit
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/arena:
  - name: kubeflow-arena-postsubmit
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/kubeflow-ci/test-worker:latest
        imagePullPolicy: Always

  kubeflow/pipelines:
  - name: kubeflow-pipeline-postsubmit
    decorate: true
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-1.10
        command:
        - ./test/postsubmit-tests-with-pipeline-deployment.sh
        args:
        - --workflow_file
        - sample_test.yaml
        - --test_result_folder
        - sample_test
        - --timeout
        - "3600"
