presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-godeps
    run_if_changed: '^((build\/|Godeps\/|vendor\/|hack\/lib\/|hack\/.*godep|staging\/).*)$'
    path_alias: "k8s.io/kubernetes"
    decorate: true
    always_run: false
    skip_report: false
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - name: main
        command:
        - runner.sh
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master
        args:
        - make
        - verify
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        env:
        # Force checks to run; we don't have remotes so we can't rely on the
        # bash/git checks to work.
        - name: KUBE_FORCE_VERIFY_CHECKS
          value: "Y"
        # Space separated list of the checks to run
        - name: WHAT
          value: "godeps staging-godeps godep-licenses"
