presubmits:
  kubernetes/kubernetes:
  # manual-release-bump-required
  - name: pull-kubernetes-typecheck
    path_alias: "k8s.io/kubernetes"
    decorate: true
    always_run: true
    skip_report: false
    # branched per release (older go versions)
    skip_branches:
    - release-1.10
    - release-1.11
    - release-1.12
    - release-1.13
    spec:
      containers:
      - name: main
        command:
        - make
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master
        args:
        - verify
        env:
        # Space separated list of the checks to run
        - name: WHAT
          value: typecheck
  - name: pull-kubernetes-typecheck
    path_alias: "k8s.io/kubernetes"
    decorate: true
    always_run: true
    skip_report: false
    branches:
    - release-1.13 # per-release job
    spec:
      containers:
      - name: main
        command:
        - make
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-1.13
        args:
        - verify
        env:
        # Space separated list of the checks to run
        - name: WHAT
          value: typecheck
  - name: pull-kubernetes-typecheck
    path_alias: "k8s.io/kubernetes"
    decorate: true
    always_run: true
    skip_report: false
    branches:
    - release-1.12
    spec:
      containers:
      - name: main
        command:
        - make
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-1.12
        args:
        - verify
        env:
        # Space separated list of the checks to run
        - name: WHAT
          value: typecheck
  - name: pull-kubernetes-typecheck
    path_alias: "k8s.io/kubernetes"
    decorate: true
    always_run: true
    skip_report: false
    branches:
    - release-1.11
    spec:
      containers:
      - name: main
        command:
        - make
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-1.11
        args:
        - verify
        env:
        # Space separated list of the checks to run
        - name: WHAT
          value: typecheck
  - name: pull-kubernetes-typecheck
    path_alias: "k8s.io/kubernetes"
    decorate: true
    always_run: true
    skip_report: false
    branches:
    - release-1.10
    spec:
      containers:
      - name: main
        command:
        - make
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-1.10
        args:
        - verify
        env:
        # Space separated list of the checks to run
        - name: WHAT
          value: typecheck

