presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-gce-csi-serial
    always_run: false
    optional: true
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-pull-kubernetes-e2e: "true"
      preset-pull-kubernetes-e2e-gce: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=150
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --extract=local
        - --gcp-node-image=gci
        - --gcp-zone=us-central1-f
        - --provider=gce
        - --runtime-config=batch/v2alpha1=true,admissionregistration.k8s.io/v1alpha1=true
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-csi-serial
        - --test_args=--ginkgo.focus=CSI.*(\[Serial\]|\[Disruptive\]) --ginkgo.skip=\[Flaky\]|\[Feature:.+\]|gcePD-external --minStartupPods=8
        - --timeout=120m
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master
        resources:
          requests:
            memory: "6Gi"
