presubmits:
  kubernetes/dns:
  - name: pull-kubernetes-dns-test
    branches:
    - master
    always_run: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/gcloud-in-go:v20171113-192bec25
        args:
        - --repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)
        - --root=/go/src
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --scenario=execute
        - --
        - "true"

periodics:
- interval: 30m
  name: ci-kubernetes-e2e-gce-alpha-api
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=80
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      # List GCE Alpha features we want to enable, separated by commas.
      - --env=GCE_ALPHA_FEATURES=NetworkTiers
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-nodes=4
      - --gcp-project=k8s-e2e-gce-alpha-api-access
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:GCEAlphaFeature\] --minStartupPods=8
      - --timeout=60m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 6h
  name: ci-kubernetes-e2e-gce-coredns-performance
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=80
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-coredns-perf
      - --env=CLUSTER_DNS_CORE_DNS=true
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-nodes=3
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:PerformanceDNS\]
      - --timeout=60m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 6h
  name: ci-kubernetes-e2e-gce-kubedns-performance
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=80
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-kubedns-perf
      - --env=CLUSTER_DNS_CORE_DNS=false
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-nodes=3
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:PerformanceDNS\]
      - --timeout=60m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 60m
  name: ci-kubernetes-e2e-gci-gce-coredns
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --env=CLUSTER_DNS_CORE_DNS=true
      - --extract=ci/latest
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 6h
  name: ci-kubernetes-e2e-gce-coredns-performance-nodecache
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=80
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-coredns-perf-cache
      - --env=CLUSTER_DNS_CORE_DNS=true
      - --env=KUBE_ENABLE_NODELOCAL_DNS=true
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-nodes=3
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:PerformanceDNS\]
      - --timeout=60m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 6h
  name: ci-kubernetes-e2e-gce-kubedns-performance-nodecache
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=80
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --cluster=gce-kubedns-perf-cache
      - --env=CLUSTER_DNS_CORE_DNS=false
      - --env=KUBE_ENABLE_NODELOCAL_DNS=true
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-nodes=3
      - --gcp-zone=us-east1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:PerformanceDNS\]
      - --timeout=60m
      - --use-logexporter
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 60m
  name: ci-kubernetes-e2e-gci-gce-coredns-nodecache
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --env=CLUSTER_DNS_CORE_DNS=true
      - --env=KUBE_ENABLE_NODELOCAL_DNS=true
      - --extract=ci/latest
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gce-ingress
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=340
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=GCE_ALPHA_FEATURES=NetworkEndpointGroup
      - --env=KUBE_GCE_ENABLE_IP_ALIASES=true
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-project-type=ingress-project
      - --gcp-zone=asia-southeast1-a
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:Ingress\]|\[Feature:NEG\] --ginkgo.skip=\[Unreleased\]
      - --timeout=320m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 60m
  name: ci-kubernetes-e2e-gci-gce-ingress-manual-network
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=200
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=CREATE_CUSTOM_NETWORK=true
      - --extract=ci/latest
      - --gcp-node-image=gci
      - --gcp-project-type=ingress-project
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Feature:Ingress\] --ginkgo.skip=\[Unreleased\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gce-ip-alias
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=70
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=KUBE_GCE_ENABLE_IP_ALIASES=true
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-nodes=4
      - --gcp-project=k8s-jenkins-gce-gci-ip-aliases
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=50m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 60m
  name: ci-kubernetes-e2e-gci-gce-ipvs
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=KUBE_PROXY_MODE=ipvs
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=ubuntu
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=30
      - --image-family=ubuntu-gke-1604-lts
      - --image-project=ubuntu-os-gke-cloud
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 60m
  name: ci-kubernetes-e2e-gci-gce-kube-dns
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --env=CLUSTER_DNS_CORE_DNS=false
      - --extract=ci/latest
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 60m
  name: ci-kubernetes-e2e-gci-gce-kube-dns-nodecache
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --env=CLUSTER_DNS_CORE_DNS=false
      - --env=KUBE_ENABLE_NODELOCAL_DNS=true
      - --extract=ci/latest
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel=30
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gce-serial-kube-dns
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=520
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=NODE_LOCAL_SSDS_EXT=1,scsi,fs
      - --env=CLUSTER_DNS_CORE_DNS=false,
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=500m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gce-serial-kube-dns-nodecache
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=520
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --env=NODE_LOCAL_SSDS_EXT=1,scsi,fs
      - --env=CLUSTER_DNS_CORE_DNS=false
      - --env=KUBE_ENABLE_NODELOCAL_DNS=true
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=500m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gke-ingress
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=320
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project-type=ingress-project
      - --gcp-zone=us-central1-f
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:Ingress\] --ginkgo.skip=\[Unreleased\] --minStartupPods=8
      - --timeout=300m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-master
