periodics:
- name: ci-test-infra-build-smoke
  interval: 2h
  agent: knative-build
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  build_spec:
    steps:
    - name: first
      image: busybox
      args: ["echo", "hello"]
    - name: second
      image: busybox
      args: ["echo", "world"]
    - name: third
      image: busybox
      args: ["cat", "config/jobs/kubernetes/test-infra/test-infra-periodics.yaml"]
- name: ci-test-infra-bazel
  interval: 1h
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190110-49573aea5-experimental
      args:
      - "--job=$(JOB_NAME)"
      - "--repo=k8s.io/test-infra=master"
      - "--service-account=/etc/service-account/service-account.json"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--scenario=kubernetes_bazel"
      - "--" # end bootstrap args, scenario args below
      - "--build=//..."
      - "--install=gubernator/test_requirements.txt"
      - "--test=//..."
      - "--test-args=--test_output=errors"
      # Bazel needs privileged mode in order to sandbox builds.
      securityContext:
        privileged: true
      resources:
        requests:
          memory: "2Gi"

- name: ci-test-infra-triage
  decorate: true
  interval: 20m
  spec:
    containers:
    - image: gcr.io/k8s-testimages/triage:latest
      imagePullPolicy: Always
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/service-account/service-account.json
      command:
        - "timeout"
      args:
        - "-t"
        - "10800"
        - "/update_summaries.sh"
      volumeMounts:
      - name: service
        mountPath: /etc/service-account
        readOnly: true
    volumes:
    - name: service
      secret:
        secretName: triage-service-account

- name: metrics-bigquery
  interval: 24h
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bigquery:v20180330-f723e8d3f
      args:
      - --scenario=execute
      - --
      - test-infra/metrics/bigquery.py
      - --
      - --bucket=gs://k8s-metrics
      - --backfill-days=90
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/service-account/service-account.json
      - name: VELODROME_INFLUXDB_CONFIG
        value: /etc/velodrome-influxdb/config.json
      volumeMounts:
      - name: service
        mountPath: /etc/service-account
        readOnly: true
      - name: influxdb
        mountPath: /etc/velodrome-influxdb
        readOnly: true
    volumes:
    - name: service
      secret:
        secretName: triage-service-account
    - name: influxdb
      secret:
        secretName: velodrome-influxdb

- name: metrics-kettle
  interval: 1h
  spec:
    containers:
    - image: gcr.io/k8s-testimages/bigquery:v20180330-f723e8d3f
      args:
      - --scenario=execute
      - --
      - test-infra/kettle/monitor.py
      - --
      - --stale=6
      - --table
      - k8s-gubernator:build.all
      - k8s-gubernator:build.week
      - k8s-gubernator:build.day
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/service-account/service-account.json
      - name: VELODROME_INFLUXDB_CONFIG
        value: /etc/velodrome-influxdb/config.json
      volumeMounts:
      - name: service
        mountPath: /etc/service-account
        readOnly: true
      - name: influxdb
        mountPath: /etc/velodrome-influxdb
        readOnly: true
    volumes:
    - name: service
      secret:
        secretName: triage-service-account
    - name: influxdb
      secret:
        secretName: velodrome-influxdb
